Create HTTP classes
UCLA-CS130/Code-Monkies pull request #13
Opened 2017-02-08 09:32 UTC by ahesselgrave

Create Request, Response, and appropriate helpers and tests.

2017-02-08 21:59 UTC, jobu95 commented on src/http/constants.h
> +#ifndef STATUS_H
For consistency shouldn't this be CONSTANTS_H?

2017-02-08 22:00 UTC, jobu95 commented on src/http/constants.h
> +				exit(-1);
I've been exiting with status 1. Do you want to switch everything to status -1?

2017-02-08 22:01 UTC, jobu95 commented on src/http/message.h
> +	std::vector<std::string> headers_;
I haven't been using trailing underscores for member variables. Do you want to from now on?

2017-02-08 22:06 UTC, jobu95 requested changes
I asked for a couple minor changes, but if you decide not to do them feel free to merge.

2017-02-08 22:18 UTC, ahesselgrave commented on src/http/constants.h
> +#ifndef STATUS_H
woops yeah, I renamed the file but forgot to change the header guards, I'll fix

2017-02-08 22:18 UTC, ahesselgrave commented on src/http/constants.h
> +				exit(-1);
Technically we should have more defined error codes, but I'll change them to 1 for consistency as a general error and we can specialize error codes later if we need it

2017-02-08 22:19 UTC, jobu95 commented on src/http/constants.h
> +				exit(-1);
Yeah I agree. Thanks.

2017-02-08 22:21 UTC, ahesselgrave commented on src/http/message.h
> +	std::vector<std::string> headers_;
I'm following the naming convention [https://google.github.io/styleguide/cppguide.html#Variable_Names](here) cause I saw it in lecture lol. I'm not attached to anything but I would prefer consistency.

2017-02-08 22:21 UTC, jobu95 commented on src/http/message.h
> +	std::vector<std::string> headers_;
Ok, I'll add trailing underscores to my member variables.

2017-02-08 22:33 UTC, ahesselgrave commented on src/http/constants.h
> +				exit(-1);
wait actually wtf I changed that to throw an exception. I guess I forgot to update the commits.

2017-02-09 02:18 UTC, ahesselgrave commented
I'm gonna assume this is ok since I changed what you requested and it passed. Gotta move forward.

2017-02-09 02:20 UTC, merged